-- ANANT JOB HUNT OS seed (generated from master workbook)
-- 1) Create your auth user, copy its UUID, replace YOUR_USER_UUID below.
-- 2) Run schema.sql first, then this file, in SQL Editor.
do $$
declare uid uuid := 'YOUR_USER_UUID';
declare cid bigint; declare jid bigint;
begin
  insert into public.companies(user_id,name,website,location,industry,contact_email,notes) values (uid,'Virtusa','https://www.virtusa.com','Hyderabad, Telangana, India','IT Services / Engineering',NULL,'Equal Opportunity Employer statement on site. Single posting tracked so far.' ) on conflict (user_id,name) do nothing;
  insert into public.companies(user_id,name,website,location,industry,contact_email,notes) values (uid,'BT Group','https://www.bt.com','IND-Bengaluru-Pritech (posting); UK Group HQ context','Telecommunications / Digital Engineering',NULL,'Purpose ''connect for good''. Culture: customer-first challengers, committed/clear/connected.' ) on conflict (user_id,name) do nothing;
  insert into public.companies(user_id,name,website,location,industry,contact_email,notes) values (uid,'Gridlex',NULL,'Hyderabad (hiring); enterprise clients','Enterprise Software (Healthcare, Biopharma, Medical Devices, Home Health & Hospice)',NULL,'Gridlex logo tagline: ONE PLATFORM ENDLESS POSSIBILITIES.' ) on conflict (user_id,name) do nothing;
  insert into public.companies(user_id,name,website,location,industry,contact_email,notes) values (uid,'Shiv Infotech (inferred from email domain)',NULL,NULL,NULL,'hr@shivinfotech.co','Company identity NOT confirmed - inferred only from email domain. Verify before interview prep.' ) on conflict (user_id,name) do nothing;
  insert into public.companies(user_id,name,website,location,industry,contact_email,notes) values (uid,'KSB',NULL,'Pune (KSB Tech Pune; global: KSB SE KGaA IT)','Pumps/Engineering + Enterprise IT',NULL,'SAP Business One rollout/support org.' ) on conflict (user_id,name) do nothing;
  insert into public.companies(user_id,name,website,location,industry,contact_email,notes) values (uid,'Lytiva',NULL,'Ahmedabad',NULL,'hr@lytiva.com','Identity NOT confirmed beyond hiring post. Verify before interview prep.' ) on conflict (user_id,name) do nothing;
  insert into public.companies(user_id,name,website,location,industry,contact_email,notes) values (uid,'Young Decade',NULL,'Indore','IT Software Solution','Not provided (WhatsApp 9644944854)','Identity NOT confirmed beyond hiring post. Verify before interview prep.' ) on conflict (user_id,name) do nothing;
  insert into public.companies(user_id,name,website,location,industry,contact_email,notes) values (uid,'Sokrati (Dentsu)',NULL,'Gurugram','Digital Marketing/Technology (Dentsu brand)',NULL,'Identity partly confirmed via JD brand tag. Verify further before interview prep.' ) on conflict (user_id,name) do nothing;
  insert into public.companies(user_id,name,website,location,industry,contact_email,notes) values (uid,'Zephyr Technologies & Solutions Pvt. Ltd.','www.zephyrtechnologies.co','Bengaluru (Ramamurthy Nagar)',NULL,'contact@zephyrtechnologies.co','Identity partly confirmed via post creative + contact/website. Verify further before interview prep.' ) on conflict (user_id,name) do nothing;
  insert into public.companies(user_id,name,website,location,industry,contact_email,notes) values (uid,'Aspirox (inferred from email domain)',NULL,NULL,NULL,'resumes@aspirox.co.in','Company identity NOT confirmed - inferred only from email domain. Verify before interview prep.' ) on conflict (user_id,name) do nothing;
  select id into cid from public.companies where user_id=uid and name='Virtusa';
  insert into public.jobs(user_id,company_id,mission_id,title,location,work_mode,employment_type,experience_requirement,source,job_url,description,required_skills,status,priority,quality_score,deadline) values (uid,cid,'ANANT-2026-0001','QA Automation Engineer','PCS HYD, Hyderabad (Hyderabad, Telangana, India)','Not provided','Not provided','0-2 Years','Company Website','https://www.virtusa.com/careers/job-search/global/en/job/VIRVIRGLOBALCREQ263151EXTERNALENUS/Software-Engineer','Job Title QA Automation Engineer | Location PCS HYD, Hyderabad | Years 0-2 | Summary: motivated detail-oriented QA Automation Engineer with strong foundation in performance testing; ensure quality/performance via automated testing; ideal for recent graduates. Responsibilities: Design/develop/execute automated test scripts for performance testing; Analyze performance results and provide actionable insights; Collaborate cross-functional; Participate in test planning/strategy; Continuously improve testing processes; Document test cases/results/defects. Mandatory: Strong performance testing concepts/tools; Automation testing frameworks; Basic Java/Python/C#; SDLC and Agile. Preferred: JMeter/LoadRunner/similar; CI/CD pipelines and Git; Web technologies and app architectures. Qualifications: Bachelor''s CS/IT/related; Strong analytical/problem-solving; Excellent communication/teamwork.','Performance testing concepts and tools; Automation testing frameworks; Basic Java/Python/C#; SDLC and Agile','APPLIED','High',78,NULL);
  select id into jid from public.jobs where user_id=uid and mission_id='ANANT-2026-0001' order by id desc limit 1;
  insert into public.applications(user_id,job_id,mission_id,stage,date_applied,xp_earned,notes) values (uid,jid,'ANANT-2026-0001','APPLIED','2026-09-07',95,'Posting showed ''filled/expired'' on verification 2026-09-07; JD text from user is source of truth. No recruiter contact provided.');
  select id into cid from public.companies where user_id=uid and name='BT Group';
  insert into public.jobs(user_id,company_id,mission_id,title,location,work_mode,employment_type,experience_requirement,source,job_url,description,required_skills,status,priority,quality_score,deadline) values (uid,cid,'ANANT-2026-0002','Associate Engineer','IND-Bengaluru-Pritech','Not specified (likely On-site/Hybrid)','Not specified','Fresher / Entry-level (implied)','Company Website','https://jobs.bt.com/BT/job/Associate-engineer/61954-en_GB/','Job Title: Associate engineer | Req ID: 61954 | Function: Engineering | Division: Networks | Location: IND-Bengaluru-Pritech | Salary: competitive | Posting 03/09/2026-07/09/2026. About: Work within BT Group telecom tech and digital engineering to build/support apps, platforms, network solutions. Impact: customer experience, network reliability, operational efficiency. Strategy: digital transformation via innovation, automation, modern practices. Doing: Develop/support software for digital/telecom services; collaborate cross-functional for reliable, secure, customer-focused solutions; learn/contribute/grow in agile environment; improve network operations. Essential: Good Java and/or Python; OOP concepts; Data Structures and Algorithms; Basic SQL and relational DBs; Git/version control; Strong analytical, problem-solving, communication.','Java and/or Python; OOP concepts; Data Structures and Algorithms; SQL and relational databases; Git/version control; Analytical, problem-solving, communication','APPLIED','High',80,'2026-09-07');
  select id into jid from public.jobs where user_id=uid and mission_id='ANANT-2026-0002' order by id desc limit 1;
  insert into public.applications(user_id,job_id,mission_id,stage,date_applied,xp_earned,notes) values (uid,jid,'ANANT-2026-0002','APPLIED','2026-09-07',95,'Req ID 61954, Division Networks, Posting 03/09/2026-07/09/2026 (deadline TODAY). Link verified live 2026-09-07, matches pasted JD. No recruiter contact provided.');
  select id into cid from public.companies where user_id=uid and name='Gridlex';
  insert into public.jobs(user_id,company_id,mission_id,title,location,work_mode,employment_type,experience_requirement,source,job_url,description,required_skills,status,priority,quality_score,deadline) values (uid,cid,'ANANT-2026-0003','Software Testing Engineer','Hyderabad - 5 Days WFO','WFO','Full-Time','0-1 Year','LinkedIn Post (Ranjith Varma)','https://www.linkedin.com/posts/activity-7501836510858723328-cmE3','Hiring Software Testing Engineers passionate about quality. Enterprise software (Healthcare/Biopharma/Medical Devices/Home Health). Role 0-1yr, Hyderabad 5d WFO, virtual interview, full-time. Skills: Manual Testing, Test Case Design & Execution, Functional, Regression, JIRA, Playwright, Selenium, JavaScript, TypeScript, Python. Manual/QA-course candidates encouraged. Mail CV to ranjithkumar@gridlex.com.','Manual Testing; Test Case Design & Execution; Functional Testing; Regression Testing; JIRA; Playwright; Selenium; JavaScript; TypeScript; Python','APPLIED','High',85,NULL);
  select id into jid from public.jobs where user_id=uid and mission_id='ANANT-2026-0003' order by id desc limit 1;
  insert into public.applications(user_id,job_id,mission_id,stage,date_applied,xp_earned,notes) values (uid,jid,'ANANT-2026-0003','APPLIED','2026-09-07',165,'Source: LinkedIn screenshot; HR mail ranjithkumar@gridlex.com; virtual interview; With_Photo resume for mail. | Email draft: D:\Anant_Job_System\Email_Drafts\Gridlex_Software_Testing_Engineer_Email_Draft.txt');
  select id into cid from public.companies where user_id=uid and name='Shiv Infotech';
  insert into public.jobs(user_id,company_id,mission_id,title,location,work_mode,employment_type,experience_requirement,source,job_url,description,required_skills,status,priority,quality_score,deadline) values (uid,cid,'ANANT-2026-0004','Not specified - General Application','Not provided','Not provided','Not provided','Fresher implied','Email (HR mail only)','Not provided','No JD provided. Mail-only application using general resume.','Not specified (no JD - general resume used)','APPLIED','Medium',60,NULL);
  select id into jid from public.jobs where user_id=uid and mission_id='ANANT-2026-0004' order by id desc limit 1;
  insert into public.applications(user_id,job_id,mission_id,stage,date_applied,xp_earned,notes) values (uid,jid,'ANANT-2026-0004','APPLIED','2026-09-07',35,'Mail-only application: no JD/role/link provided; general resume + email draft. Company name inferred from domain, not confirmed. | Email draft: D:\Anant_Job_System\Email_Drafts\Shiv Infotech_General_Email_Draft.txt');
  select id into cid from public.companies where user_id=uid and name='KSB';
  insert into public.jobs(user_id,company_id,mission_id,title,location,work_mode,employment_type,experience_requirement,source,job_url,description,required_skills,status,priority,quality_score,deadline) values (uid,cid,'ANANT-2026-0005','Associate Software Developer','Pune (On-site)','On-site','Full-Time','0-3 Years (SAP B1)','Company Website (Workday)','https://ksb.wd3.myworkdayjobs.com/en-US/KSB_ExternalCareerSite/job/Pune/Associate-Software-Developer_JR_30575','SAP B1 EASD Associate Software Developer, KSB Tech Pune, with KSB SE KGaA IT. Support tickets per SLA, resolve technical issues, functional-to-technical execution, B1 rollouts, global projects, partner coordination, business-user interaction, continuous improvement. Skills: SAP B1 config + module integration, go-live support, MS SQL/HANA + queries, Crystal Reports, C# .Net Add-Ons/B1UP, B1if/service layer/HANA reporting/Python (advantage). Attributes: communication, global team, travel.','SAP B1 technical; MS SQL/HANA + queries; Crystal Reports; C# .Net Add-Ons/B1UP; analytical','APPLIED','Medium',55,NULL);
  select id into jid from public.jobs where user_id=uid and mission_id='ANANT-2026-0005' order by id desc limit 1;
  insert into public.applications(user_id,job_id,mission_id,stage,date_applied,xp_earned,notes) values (uid,jid,'ANANT-2026-0005','APPLIED','2026-09-07',48,'Req JR_30575, posted ~5 days ago. Workday blocked verification fetch; pasted JD is source. Core SAP B1 ask missing from profile - weak overall match, SQL/Python transferables emphasized.');
  select id into cid from public.companies where user_id=uid and name='Lytiva';
  insert into public.jobs(user_id,company_id,mission_id,title,location,work_mode,employment_type,experience_requirement,source,job_url,description,required_skills,status,priority,quality_score,deadline) values (uid,cid,'ANANT-2026-0006','Node.js/Next.js Developer Intern','Ahmedabad','Not provided','Internship','Fresher (Intern)','LinkedIn Post (Lytiva company page)','Not provided (LinkedIn post screenshot)','Hiring Interns at Lytiva. Open: (1) Node.js/Next.js Developer Intern, (2) Angular/React Developer Intern, (3) Web Designer Intern (HTML, CSS). Apply: CV to hr@lytiva.com. Location: Ahmedabad.','Node.js; Next.js (React/Angular/Web-Designer variants also listed)','APPLIED','High',92,NULL);
  select id into jid from public.jobs where user_id=uid and mission_id='ANANT-2026-0006' order by id desc limit 1;
  insert into public.applications(user_id,job_id,mission_id,stage,date_applied,xp_earned,notes) values (uid,jid,'ANANT-2026-0006','APPLIED','2026-09-07',98,'Posted ~1h ago. Also hiring Angular/React Intern + Web Designer Intern (HTML/CSS) - Node/Next chosen as strongest fit. Email draft: Email_Drafts/Lytiva_Nodejs_Nextjs_Developer_Intern_Email_Draft.txt');
  select id into cid from public.companies where user_id=uid and name='Young Decade (IT Software Solution)';
  insert into public.jobs(user_id,company_id,mission_id,title,location,work_mode,employment_type,experience_requirement,source,job_url,description,required_skills,status,priority,quality_score,deadline) values (uid,cid,'ANANT-2026-0007','Flutter Developer (Fresher)','Indore (On-site)','On-site','Full-Time','Fresher (Flutter internship mandatory; Indore-only)','LinkedIn Post (Young Decade)','Not provided (LinkedIn post screenshot)','Flutter Developer Fresher, Indore on-site. Requires: strong Flutter & Dart; Flutter internship mandatory; API Integration & State Management basics; problem-solving; Indore-based only; face-to-face interview only, no virtual. Apply: resume on WhatsApp 9644944854.','Flutter & Dart (strong); Flutter internship mandatory; API Integration & State Management basics; problem-solving','APPLIED','Low',50,NULL);
  select id into jid from public.jobs where user_id=uid and mission_id='ANANT-2026-0007' order by id desc limit 1;
  insert into public.applications(user_id,job_id,mission_id,stage,date_applied,xp_earned,notes) values (uid,jid,'ANANT-2026-0007','APPLIED','2026-09-07',30,'WEAK MATCH + location gate: Flutter/Dart absent, no Flutter internship, Indore-only eligibility unmet (Pune-based). Face-to-face only. Built honestly with growth-intent framing; prioritize Lytiva. WhatsApp draft: Email_Drafts/Young_Decade_Flutter_Developer_WhatsApp_Draft.txt');
  select id into cid from public.companies where user_id=uid and name='Sokrati (Dentsu)';
  insert into public.jobs(user_id,company_id,mission_id,title,location,work_mode,employment_type,experience_requirement,source,job_url,description,required_skills,status,priority,quality_score,deadline) values (uid,cid,'ANANT-2026-0008','Entry-Level Full Stack Developer','Gurugram','Not provided','Full-Time Permanent','0-1 Years (internship/project/hackathon)','LinkedIn -> Company Website (Workday)','https://dentsuaegis.wd3.myworkdayjobs.com/DAN_GLOBAL/job/Gurugram/Developer_R1128610?source=LinkedIn','Entry-level full-stack: React.js frontends; Python (Flask/Django) REST backends; frontend-backend + third-party integrations; MySQL/MongoDB modeling; clean documented code; reviews, manual/API testing (Postman), debugging; cross-functional delivery; perf/usability fixes. Required: HTML/CSS/JS/React; Python + Flask/Django; REST; MySQL/MongoDB; Git; Postman; analytical; communication. Good-to-have: LLM/AI integration; scraping/extraction; ML-assisted analysis; full-stack internship; hackathons; GitHub portfolio. Qual: Bachelor CS/IT+, 0-1 yrs via internship/project/hackathon.','React.js; Python (Flask/Django); REST APIs; MySQL/MongoDB; Git; Postman; analytical; communication','APPLIED','High',90,'2026-09-30');
  select id into jid from public.jobs where user_id=uid and mission_id='ANANT-2026-0008' order by id desc limit 1;
  insert into public.applications(user_id,job_id,mission_id,stage,date_applied,xp_earned,notes) values (uid,jid,'ANANT-2026-0008','APPLIED','2026-09-07',75,'Req R1128610, deadline Sep 30 2026 (22 days). Flask/Django, Postman, hackathons NOT in profile - marked partial/missing; Python kept (Basic). Strong match otherwise.');
  select id into cid from public.companies where user_id=uid and name='Zephyr Technologies & Solutions Pvt. Ltd.';
  insert into public.jobs(user_id,company_id,mission_id,title,location,work_mode,employment_type,experience_requirement,source,job_url,description,required_skills,status,priority,quality_score,deadline) values (uid,cid,'ANANT-2026-0009','AI Developer (Freshers welcome)','Bengaluru (Ramamurthy Nagar office)','Not provided','Not provided','Freshers and Experienced','LinkedIn Post (Zephyr page via Way2Freshers)','Not provided (LinkedIn post via Way2Freshers share)','Hiring AI Developer for Bengaluru team, AI-driven projects. Freshers and experienced welcome. Contact contact@zephyrtechnologies.co, www.zephyrtechnologies.co. Office: #9 SP Naidu Layout, Ramamurthy Nagar, New Police Station Road, Bengaluru 560016.','AI development; AI-driven projects (details minimal in post)','APPLIED','High',88,NULL);
  select id into jid from public.jobs where user_id=uid and mission_id='ANANT-2026-0009' order by id desc limit 1;
  insert into public.applications(user_id,job_id,mission_id,stage,date_applied,xp_earned,notes) values (uid,jid,'ANANT-2026-0009','APPLIED','2026-09-07',98,'AI Developer, Bengaluru team. Contact contact@zephyrtechnologies.co. Email draft: Email_Drafts/Zephyr_AI_Developer_Email_Draft.txt');
  select id into cid from public.companies where user_id=uid and name='Aspirox';
  insert into public.jobs(user_id,company_id,mission_id,title,location,work_mode,employment_type,experience_requirement,source,job_url,description,required_skills,status,priority,quality_score,deadline) values (uid,cid,'ANANT-2026-0010','Not specified - General Application','Not provided','Not provided','Not provided','Fresher implied','Email (HR mail only)','Not provided','No JD provided. Mail-only application using general resume.','Not specified (no JD - general resume used)','APPLIED','Medium',60,NULL);
  select id into jid from public.jobs where user_id=uid and mission_id='ANANT-2026-0010' order by id desc limit 1;
  insert into public.applications(user_id,job_id,mission_id,stage,date_applied,xp_earned,notes) values (uid,jid,'ANANT-2026-0010','APPLIED','2026-09-07',35,'Mail-only application: no JD/role/link provided; general resume + email draft. Company name inferred from domain, not confirmed.');
  insert into public.resume_versions(user_id,job_id,file_name,version_label,has_photo,storage_path,notes) select uid, (select id from public.jobs where user_id=uid and mission_id='ANANT-2026-0001' limit 1),'Anant Prabhudesai - Virtusa - QA Automation Engineer.pdf','v1',false,'D:\Anant_Job_System\Resumes\Anant Prabhudesai - Virtusa - QA Automation Engineer.pdf','Strict anti-hallucination build: no JMeter/LoadRunner/Selenium/TestNG claims; no test-case metrics invented.';
  insert into public.resume_versions(user_id,job_id,file_name,version_label,has_photo,storage_path,notes) select uid, (select id from public.jobs where user_id=uid and mission_id='ANANT-2026-0002' limit 1),'Anant Prabhudesai - BT Group - Associate Engineer.pdf','v1',false,'D:\Anant_Job_System\Resumes\Anant Prabhudesai - BT Group - Associate Engineer.pdf','Strict build: no DSA, no telecom-domain experience invented.';
  insert into public.resume_versions(user_id,job_id,file_name,version_label,has_photo,storage_path,notes) select uid, (select id from public.jobs where user_id=uid and mission_id='ANANT-2026-0003' limit 1),'Anant Prabhudesai - Gridlex - Software Testing Engineer.pdf','v1',true,'D:\Anant_Job_System\Resumes\With_Photo\Anant Prabhudesai - Gridlex - Software Testing Engineer.pdf','With_Photo for HR mail. Honest gaps: Manual Testing, JIRA, Playwright, Selenium, TypeScript, QA course.';
  insert into public.resume_versions(user_id,job_id,file_name,version_label,has_photo,storage_path,notes) select uid, (select id from public.jobs where user_id=uid and mission_id='ANANT-2026-0002' limit 1),'Anant Prabhudesai - BT Group - Associate Engineer.pdf','v1-no-photo',false,'D:\Anant_Job_System\Resumes\No_Photo\Anant Prabhudesai - BT Group - Associate Engineer.pdf','No-photo ATS version in No_Photo folder. Rule: portal link = No_Photo; HR/company email = With_Photo + email draft.';
  insert into public.resume_versions(user_id,job_id,file_name,version_label,has_photo,storage_path,notes) select uid, (select id from public.jobs where user_id=uid and mission_id='ANANT-2026-0004' limit 1),'Anant Prabhudesai - Shiv Infotech - General Resume.pdf','v1-general',true,'D:\Anant_Job_System\Resumes\With_Photo\Anant Prabhudesai - Shiv Infotech - General Resume.pdf','Mail-only rule: general resume + email draft. No tailoring possible without JD.';
  insert into public.resume_versions(user_id,job_id,file_name,version_label,has_photo,storage_path,notes) select uid, (select id from public.jobs where user_id=uid and mission_id='ANANT-2026-0005' limit 1),'Anant Prabhudesai - KSB - Associate Software Developer.pdf','v1',false,'D:\Anant_Job_System\Resumes\No_Photo\Anant Prabhudesai - KSB - Associate Software Developer.pdf','No_Photo for portal. Weak-match application logged honestly.';
  insert into public.resume_versions(user_id,job_id,file_name,version_label,has_photo,storage_path,notes) select uid, (select id from public.jobs where user_id=uid and mission_id='ANANT-2026-0006' limit 1),'Anant Prabhudesai - Lytiva - Nodejs Nextjs Developer Intern.pdf','v1',true,'D:\Anant_Job_System\Resumes\With_Photo\Anant Prabhudesai - Lytiva - Nodejs Nextjs Developer Intern.pdf','With_Photo for HR mail. Strong stack match.';
  insert into public.resume_versions(user_id,job_id,file_name,version_label,has_photo,storage_path,notes) select uid, (select id from public.jobs where user_id=uid and mission_id='ANANT-2026-0007' limit 1),'Anant Prabhudesai - Young Decade - Flutter Developer.pdf','v1',true,'D:\Anant_Job_System\Resumes\With_Photo\Anant Prabhudesai - Young Decade - Flutter Developer.pdf','With_Photo for direct apply. Weak match logged honestly.';
  insert into public.resume_versions(user_id,job_id,file_name,version_label,has_photo,storage_path,notes) select uid, (select id from public.jobs where user_id=uid and mission_id='ANANT-2026-0008' limit 1),'Anant Prabhudesai - Sokrati - Full Stack Developer.pdf','v1',false,'D:\Anant_Job_System\Resumes\No_Photo\Anant Prabhudesai - Sokrati - Full Stack Developer.pdf','No_Photo for portal. Strong match.';
  insert into public.resume_versions(user_id,job_id,file_name,version_label,has_photo,storage_path,notes) select uid, (select id from public.jobs where user_id=uid and mission_id='ANANT-2026-0009' limit 1),'Anant Prabhudesai - Zephyr - AI Developer.pdf','v1',true,'D:\Anant_Job_System\Resumes\With_Photo\Anant Prabhudesai - Zephyr - AI Developer.pdf','With_Photo for company mail. Strong thematic match (applied AI + specialization).';
  insert into public.resume_versions(user_id,job_id,file_name,version_label,has_photo,storage_path,notes) select uid, (select id from public.jobs where user_id=uid and mission_id='ANANT-2026-0010' limit 1),'Anant Prabhudesai - Aspirox - General Resume.pdf','v1-general',true,'D:\Anant_Job_System\Resumes\With_Photo\Anant Prabhudesai - Aspirox - General Resume.pdf','Mail-only rule: general resume + email draft. No tailoring possible without JD.';
  insert into public.email_drafts(user_id,job_id,to_email,subject,body,status) select uid, (select id from public.jobs where user_id=uid and mission_id='ANANT-2026-0003' limit 1),'ranjithkumar@gridlex.com','Application for Software Testing Engineer (0–1 Year, Hyderabad) – Anant Prabhudesai | MCA 2026 Fresher','
Dear Mr. Ranjith Varma,

I came across your LinkedIn post regarding the Software Testing Engineer opening at Gridlex, and I would like to apply for the same.

I am a MCA candidate (AI/ML Specialization, SVIT Vasad, 2026) with a BCA in Gaming Technology and 10 months of combined internship experience across two software development roles. During my internships I worked hands-on with JavaScript and Python (Basic), built and validated REST APIs, verified authentication and role-based access flows, and shipped full-stack products with measurable quality signals (5+ validated REST endpoints, zero unauthorized access incidents, 10+ concurrent users, sub-2-second load times), following Agile sprint cycles and company coding standards under senior engineer guidance.

I am comfortable relocating to Hyderabad for a 5-days work-from-office role and am available for a virtual interview at your convenience. I am keen to grow in manual testing and automation tools while contributing my JavaScript/Python and API-validation fundamentals to Gridlex''s quality-focused team.

Please find my resume attached for your consideration. I would be glad to discuss my background further.

Thank you for your time.

Best regards,
Anant Prabhudesai
Hinjewadi Phase 3, Pune | Open to Relocate to Hyderabad
8160551448 | anantprabhudesai444@gmail.com
LinkedIn: https://www.linkedin.com/in/anant-prabhudesai-93982a207/
GitHub: https://github.com/AnantPrabhudesai01','DRAFTED';
  insert into public.email_drafts(user_id,job_id,to_email,subject,body,status) select uid, (select id from public.jobs where user_id=uid and mission_id='ANANT-2026-0004' limit 1),'hr@shivinfotech.co','Application for Entry-Level Software Developer Role – Anant Prabhudesai | MCA 2026 Fresher','
Dear Hiring Manager,

I would like to apply for an entry-level software developer opportunity at Shiv Infotech.

I am a MCA candidate (AI/ML Specialization, SVIT Vasad, 2026) with a BCA in Gaming Technology and 10 months of combined internship experience across two software development roles. During my internships I built 3 full-stack products using React.js, Next.js, Node.js, REST APIs, MySQL/MongoDB and JWT/OAuth authentication, with CI/CD deployment and Agile delivery under senior engineer guidance.

I am open to relocating and available to join at your convenience. Please find my resume attached for your consideration. I would welcome the chance to discuss how I can contribute to your team.

Thank you for your time and consideration.

Best regards,
Anant Prabhudesai
Hinjewadi Phase 3, Pune | Open to Relocate
8160551448 | anantprabhudesai444@gmail.com
LinkedIn: https://www.linkedin.com/in/anant-prabhudesai-93982a207/
GitHub: https://github.com/AnantPrabhudesai01','DRAFTED';
  insert into public.email_drafts(user_id,job_id,to_email,subject,body,status) select uid, (select id from public.jobs where user_id=uid and mission_id='ANANT-2026-0010' limit 1),'resumes@aspirox.co.in','Application for Entry-Level Software Developer Role – Anant Prabhudesai | MCA 2026 Fresher','
Dear Hiring Manager,

I would like to apply for an entry-level software developer opportunity at Aspirox.

I am a MCA candidate (AI/ML Specialization, SVIT Vasad, 2026) with a BCA in Gaming Technology and 10 months of combined internship experience across two software development roles. During my internships I built 3 full-stack products using React.js, Next.js, Node.js, REST APIs, MySQL/MongoDB and JWT/OAuth authentication, with CI/CD deployment and Agile delivery under senior engineer guidance.

I am open to relocating and available to join at your convenience. Please find my resume attached for your consideration. I would welcome the chance to discuss how I can contribute to your team.

Thank you for your time and consideration.

Best regards,
Anant Prabhudesai
Hinjewadi Phase 3, Pune | Open to Relocate
8160551448 | anantprabhudesai444@gmail.com
LinkedIn: https://www.linkedin.com/in/anant-prabhudesai-93982a207/
GitHub: https://github.com/AnantPrabhudesai01','DRAFTED';
  insert into public.email_drafts(user_id,job_id,to_email,subject,body,status) select uid, (select id from public.jobs where user_id=uid and mission_id='ANANT-2026-0006' limit 1),'hr@lytiva.com','Application for Node.js/Next.js Developer Intern – Anant Prabhudesai | MCA 2026 Fresher','
Dear Hiring Manager,

I came across Lytiva''s LinkedIn post regarding the Node.js/Next.js Developer Intern opening, and I would like to apply for the same.

I am a MCA candidate (AI/ML Specialization, SVIT Vasad, 2026) with a BCA in Gaming Technology and 10 months of combined internship experience across two software development roles. My core hands-on stack is exactly Node.js, Next.js and React.js — I have built and deployed 3 full-stack products with Express.js REST APIs (5+ validated endpoints), JWT/OAuth authentication, MySQL/MongoDB data layers and automated CI/CD pipelines, delivering in Agile sprint cycles under senior engineer guidance.

I am open to relocating to Ahmedabad and available to join at your convenience. Please find my resume attached for your consideration. I would welcome the chance to discuss how I can contribute to your team.

Thank you for your time and consideration.

Best regards,
Anant Prabhudesai
Hinjewadi Phase 3, Pune | Open to Relocate to Ahmedabad
8160551448 | anantprabhudesai444@gmail.com
LinkedIn: https://www.linkedin.com/in/anant-prabhudesai-93982a207/
GitHub: https://github.com/AnantPrabhudesai01','DRAFTED';
  insert into public.email_drafts(user_id,job_id,to_email,subject,body,status) select uid, (select id from public.jobs where user_id=uid and mission_id='ANANT-2026-0009' limit 1),'contact@zephyrtechnologies.co','Application for AI Developer (Fresher) – Anant Prabhudesai | MCA 2026, AI/ML Specialization','
Dear Hiring Manager,

I came across Zephyr Technologies & Solutions Pvt. Ltd.''s LinkedIn post regarding the AI Developer opening in Bengaluru, and I would like to apply as a fresher.

I am a MCA candidate in AI/ML Specialization (SVIT Vasad, 2026) with a BCA in Gaming Technology and 10 months of combined internship experience across two software development roles. Most relevantly, I have shipped an AI-powered product that integrates OCR with the Gemini API for automated business-card data extraction, including tiered-subscription logic and automated email workflows for enterprise users. My supporting base includes Python (Basic), JavaScript, REST API development and integration, MySQL/MongoDB data layers and Agile delivery with Git/CI-CD under senior engineer guidance.

I am open to relocating to Bengaluru and excited to grow on real-world AI-driven projects with your team. Please find my resume attached for your consideration. I would welcome the chance to discuss my background further.

Thank you for your time and consideration.

Best regards,
Anant Prabhudesai
Hinjewadi Phase 3, Pune | Open to Relocate to Bengaluru
8160551448 | anantprabhudesai444@gmail.com
LinkedIn: https://www.linkedin.com/in/anant-prabhudesai-93982a207/
GitHub: https://github.com/AnantPrabhudesai01','DRAFTED';
  insert into public.contacts(user_id,company_id,name,role_title,contact_type,email,phone,notes) select uid, (select id from public.companies where user_id=uid and name='Gridlex'),'Ranjith Varma','HR Operations Specialist | Talent Acquisition Specialist','HR','ranjithkumar@gridlex.com',NULL,'Posted hiring update 2d ago; 3rd+ connection; email from post screenshot.';
  insert into public.contacts(user_id,company_id,name,role_title,contact_type,email,phone,notes) select uid, (select id from public.companies where user_id=uid and name='Young Decade'),'Not provided (WhatsApp only)','Not provided','Other',NULL,'9644944854','Application channel is WhatsApp only; no named person or email.';
end $$;